# Generated by Django 4.1.1 on 2023-02-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.TextField(default="My note"),
        ),
    ]
